# NumPy

© Advanced Analytics, Amir Ben Haim, 2024

Use the hints to answer the questions

## Exercise 1

Import the numpy package under the name `np`

(**hint**: import … as …)

In [1]:
import numpy as np


## Exercise 2

Create a zeros vector of size 10

(**hint**: np.zeros)

In [55]:
a= np.zeros([10])

## Exercise 3

How to find the memory size of any array

(**hint**: size, itemsize)

In [56]:
print(a.itemsize)
print(a.size)

8
10


## Exercise 4

Create a null vector of size 10 but the fifth value which is 1 
(**hint**: array\[4\])

In [59]:
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Exercise 5

Create a vector with values ranging from 10 to 49

(**hint**: np.arange)

In [62]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Exercise 6

Reverse a vector (first element becomes last)

(**hint**: array\[::-1\])

In [70]:
a=a[::-1]
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Exercise 7

Create a 3x3 matrix with values ranging from 0 to 8

(**hint**: reshape)

In [79]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Exercise 8

Find indices of non-zero elements from \[1,2,0,0,4,0\]

(**hint**: np.nonzero)

In [82]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

## Exercise 9

Create a 3x3 identity matrix

a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros

(**hint**: np.eye)

In [107]:
 np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Exercise 10

Create a 3x3x3 array with random values

(**hint**: np.random.random)

In [110]:
np.random.random([3,3,3])

array([[[0.04121497, 0.9473753 , 0.92178215],
        [0.72549894, 0.56625286, 0.7939886 ],
        [0.51374802, 0.02656937, 0.31349534]],

       [[0.32519545, 0.19237163, 0.69424712],
        [0.13267432, 0.170371  , 0.24597697],
        [0.57726181, 0.07440414, 0.25876449]],

       [[0.47915264, 0.71677255, 0.80261564],
        [0.66436624, 0.42049935, 0.56443502],
        [0.50710086, 0.58729741, 0.94570202]]])

## Exercise 11

Create a 10x10 array with random values and find the minimum and maximum values

(**hint**: min, max)

In [116]:
a= np.random.random([10,10])
print(f"{np.max(a)} , {np.min(a)}")

0.9938958088596491 , 0.0052810918097006


or

## Exercise 12

Create a random vector of size 30 and find the mean value

(**hint**: mean)

In [117]:
a= np.random.random([10,10])
print(f"{np.mean(a)}")

0.5321971436021674


## Exercise 13

Create a 2d array with 1 on the border and 0 inside

(**hint**: array\[1:-1, 1:-1\])

In [138]:
a = np.zeros([2,10])
a[:,[0,-1]]= 1
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Exercise 14

How to add a border (filled with 0's) around an existing array?

(**hint**: np.pad)

In [158]:
np.pad(np.ones([5,5]),1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Exercise 15

What is the result of the following expression?

(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 0.1 * 3
```

In [160]:
print ( 0 * np.nan)
print ( np.nan == np.nan)
print ( np.inf > np.nan)
print ( np.nan - np.nan)
print ( np.nan in set([np.nan]))
print (  0.3 == 0.1 * 3)

nan
False
False
nan
True
False


## Exercise 16

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

(**hint**: np.diag)

In [174]:
np.diag(np.arange(1,5),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## Exercise 17

Create a 8x8 matrix and fill it with a checkerboard pattern

(**hint**: array\[::2\])

In [200]:
a= np.ones([9*9])
a[::2]=0
a= a.reshape([9,9])[:-1,:-1]

a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Exercise 18

Create a checkerboard 8x8 matrix using the "tile" function

(**hint**: np.tile)

In [212]:
np.tile([[0,1],[1,0]],[4,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])